#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaFPS

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaFPS.AthenaFPS_C
// 0x0008 (0x0260 - 0x0258)
class UAthenaFPS_C final  : public UAthenaFPSBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ShowFPSChanged(bool bShowFPS, bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, ESlateVisibility K2Node_Select_Default);
	void Construct();
	void ExecuteUbergraph_AthenaFPS(int32 EntryPoint, TDelegate<void(bool bShowFPS)> K2Node_CreateDelegate_OutputDelegate, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AFortPlayerController* K2Node_DynamicCast_AsFort_Player_Controller, bool K2Node_DynamicCast_bSuccess);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaFPS_C">();
	}
	static class UAthenaFPS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaFPS_C>();
	}
};

}

